# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rpalkar04' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rpalkar04


pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'

pod 'Alamofire', '~> 4.7'
pod 'AlamofireImage', '~> 3.3'
pod 'Cosmos', '~> 15.0'

end
